# FROM betrybe/docker-compose-example-frontend:v1
# ENTRYPOINT [ "npm" ]
# CMD [ "start" ]

# Reconstruindo a imagem docker:

FROM betrybe/docker-compose-example-frontend:v2
ENTRYPOINT [ "npm" ]
CMD [ "start" ]

# Para deixar nítido que as imagens precisam ser construídas novamente usando compose, utiliza-se a flag --build, junto com o comando | docker-compose up |